version: '3.9'

services:
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: postgresql-compose-db:latest
    container_name: postgres-compose-up
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./log:/var/log/example/postgresql
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: -c config_file=/etc/postgresql/postgresql.conf
