version: '3.9'

services:
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: my-postgresql:latest
    container_name: mydb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./log:/var/log/example/postgresql
      - ./data/postgresql:/var/lib/postgresql/data
      - ./sql:/tmp/sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: -c config_file=/etc/postgresql/postgresql.conf

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
